security:
  auth:
    # List of user ids that are granted full permission to all collections, reports & dashboards
    # Note: For reports these users are still required to be granted access to the corresponding process/decision
    # definitions in Camunda Platform Admin
    superUserIds: [demo]
    
engines:
  'camunda-bpm':
    rest: http://camunda-platform:8080/engine-rest
    webapps:
      endpoint: http://camunda-platform:8080/camunda
      enabled: true
    name: default
    importEnabled: true
    authentication:
      enabled: true
      user: demo
      password: demo
